name: hookahorder_owner_app
description: A new Flutter project.
version: 1.0.0+1

environment: {sdk: '>=2.18.2 <3.0.0'}

dependencies:
  flutter: {sdk: flutter}
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.2.0
  logger: any
  get_it: ^7.2.0
  injectable: ^2.1.0
  chopper: ^6.0.0
  json_annotation: ^4.7.0
  dio: ^4.0.6
  flutter_native_splash: ^2.2.16
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets: [assets/img/]
  fonts: []

flutter_native_splash:
  background_image: assets/img/initial_background.png
  android_gravity: fill
  ios_content_mode: scaleToFill
  android_12: {image: assets/img/initial_icon.png}
