name: hookahorder_owner_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter: {sdk: flutter}
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  freezed_annotation: ^2.4.1
  logger: any
  get_it: ^7.6.0
  injectable: ^2.1.2
  chopper: ^7.0.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  mask_text_input_formatter: ^2.5.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  jwt_decode: ^0.3.1
  flutter_ringtone_player: ^3.2.0
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.0+1
  collection: ^1.17.1
  firebase_core_web: ^2.7.0


dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.3.2
  injectable_generator: ^2.1.6
  chopper_generator: ^7.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets: [assets/img/]
  fonts: []