name: hookahorder_owner_app
description: A new Flutter project.
version: 1.0.0+1

environment: {sdk: '>=2.18.2 <3.0.0'}

dependencies:
  flutter: {sdk: flutter}
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0
  freezed_annotation: ^2.2.0
  logger: any
  get_it: ^7.3.0
  injectable: ^2.1.1
  chopper: ^6.1.1
  json_annotation: ^4.8.0
  dio: ^5.1.1
  mask_text_input_formatter: ^2.4.0
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  jwt_decode: ^0.3.1
  flutter_ringtone_player: ^3.2.0
  intl: ^0.18.1
  flutter_local_notifications: ^14.0.0
  flutter_background_service: ^2.4.6
  collection: ^1.17.0


dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets: [assets/img/]
  fonts: []